export const ANSWER_QUESTION = 'ANSWER_QUESTION'
export const SUBMIT_SURVEY = 'SUBMIT_SURVEY'
export const SUBMIT_SURVEY_REQUEST = 'SUBMIT_SURVEY_REQUEST'
export const SUBMIT_SURVEY_SUCCESS = 'SUBMIT_SURVEY_SUCCESS'
export const SUBMIT_SURVEY_FAILURE = 'SUBMIT_SURVEY_FAILURE'


