export const LOG_IN = 'LOG_IN'
export const SAVE_LOGIN_INPUT = 'SAVE_LOGIN_INPUT'
export const LOG_IN_FAILED = 'LOG_IN_FAILED'
export const LOG_IN_RESTART = 'LOG_IN_RESTART'
export const DEMO_USER = 'DEMO_USER'
