export const SAVE_MATCH_DATA = 'SAVE_MATCH_DATA'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const SAVE_INPUT = 'SAVE_INPUT'
export const MATCH_LOGOUT = 'MATCH_LOGOUT'
export const CLEAR_CURRENT_MATCH_DATA = 'CLEAR_CURRENT_MATCH_DATA'

