export const PROFILE = 'PROFILE'
export const PROFILE_LOGOUT = 'PROFILE_LOGOUT'
export const CONNECT_REQUEST = 'CONNECT_REQUEST'
export const EDIT_USER_INFO = 'EDIT_USER_INFO'
export const SAVE_PROFILE_INPUT = 'SAVE_PROFILE_INPUT'
export const DELETE_PROFILE_INPUT = 'DELETE_PROFILE_INPUT'
export const UPDATE_POLL_QUESTION = 'UPDATE_POLL_QUESTION'

