export const RECOVER_PASSWORD = 'RECOVER_PASSWORD'
export const RECOVER_PASSWORD_FAILED = 'RECOVER_PASSWORD_FAILED'
export const SAVE_RECOVER_PASSWORD_INPUT = "SAVE_RECOVER_PASSWORD_INPUT"
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED'
